# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.box = "timveil/centos7-hdp-base"
	config.vm.box_check_update = true

	config.vm.hostname = "geomesa"

	config.vbguest.auto_update = true
	config.vbguest.no_remote = false
	config.vbguest.no_install = false

	config.vm.network "private_network", type: "dhcp"

	config.vm.define "geomesa"
	config.vm.provider "virtualbox" do |vb|
		vb.gui = false
		vb.cpus = 4
		vb.name = "geomesa"
		vb.memory = "8192"
	end

	if Vagrant.has_plugin?("vagrant-proxyconf")
	  config.proxy.http     = ""
	  config.proxy.https    = ""
	  config.proxy.no_proxy = ""
	end

	 config.vm.provision :shell, :inline  => '
	 export VERSION=1.3.4

	 sudo yum install epel-release -y
	 sudo yum -y update
	 sudo yum install -y java-1.8.0-openjdk mc vim maven

	 cd /tmp
	 wget http://repo.locationtech.org/content/repositories/geomesa-releases/org/locationtech/geomesa/geomesa-hbase-dist_2.11/$VERSION/geomesa-hbase-dist_2.11-$VERSION-bin.tar.gz
	 '
end
